import { useEffect, useContext } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { FaHubspot } from "react-icons/fa";
import { AuthContext } from 'pages/_app';

import type { LayoutProps } from './types';

import styles from './styles.module.scss';

function Layout({
  children,
  className,
  toggle,
  title,
  isAuth,
}: LayoutProps) {
    const { push } = useRouter();
    const { credentials, setCredentials } = useContext(AuthContext);

  useEffect( () =>
  { 
    const user = sessionStorage.getItem( "TaskManagement" );
    if ( !user || !credentials ){
        push('/');
      }
      
      setCredentials( JSON.parse(user) );
  }, [] );
  

  const handleLogOut = () => {
      sessionStorage.removeItem( "TaskManagement" );
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>{ title || 'Task management' } </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <header>
        <nav className={ styles.navbar }>
          <div className = {styles.navLeft}>
              <span className = {styles.logo}><FaHubspot className = {styles.logoImg}/> Task Management</span>
          </div>
          <div className = {styles.navRight} onClick={handleLogOut}>
            { credentials?.email ? "Log Out" : null }
          </div>
        </nav>
        </header>
        <main className={styles.main}>
          {children}
        </main>
        <footer className={styles.footer}>
        <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
      </div>
  );
}

export default Layout;
